---
development:
  cloud_name: hisagtep6
  api_key: '875288561886986'
  api_secret: 2MD7_Jz3lq6FdmAz8MUz1vOwwWE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hisagtep6
  api_key: '875288561886986'
  api_secret: 2MD7_Jz3lq6FdmAz8MUz1vOwwWE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hisagtep6
  api_key: '875288561886986'
  api_secret: 2MD7_Jz3lq6FdmAz8MUz1vOwwWE
  enhance_image_tag: true
  static_image_support: false
