development: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: password
  pool: 5
  timeout: 5000
  database: bookmark_dev

test:
  <<: *default
  database: bookmark_test
